# Generated by Django 2.1.5 on 2021-11-25 07:59

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=200)),
                ('board_context', models.TextField()),
                ('board_like_cnt', models.IntegerField()),
                ('board_dt', models.DateField( default = datetime.now())),
                ('board_up_dt', models.DateField(default = datetime.now())),
                ('board_like', models.CharField(max_length=200)),
            ],
        ),
    ]
