# Generated by Django 2.1.5 on 2021-11-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardtable',
            name='board_user',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
