# Generated by Django 2.1.5 on 2021-11-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardtable_board_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtable',
            name='board_dt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='boardtable',
            name='board_up_dt',
            field=models.DateField(),
        ),
    ]
