# Generated by Django 2.1.5 on 2021-11-26 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20211126_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtable',
            name='board_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 17, 30, 52, 45580)),
        ),
        migrations.AlterField(
            model_name='boardtable',
            name='board_up_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 17, 30, 52, 45603)),
        ),
    ]
