# Generated by Django 2.1.5 on 2021-11-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_pwd', models.CharField(max_length=200)),
                ('user_like', models.CharField(max_length=200)),
                ('user_like_borad', models.CharField(max_length=200)),
            ],
        ),
    ]
